#!/bin/sh
#
# Start local daemon
#
# Usage: dstart <daemon>
#
if [ X"$1" != X"" ]; then
	env $1=YES sudo sh /etc/rc.local \
	| sed 's/starting local daemons/Started/'
else
	echo "Usage: dstart <daemon>"
fi
